server:
  port: 8080

spring:
  application:
    name: goodjob
  batch:
    jdbc:
      initialize-schema: always
  profiles:
    active: local

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: message/messages
    encoding: UTF-8

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ENC(ul/6POjcQljJQlL38MpYWmXCJDMgudx31KPb2M/kVJ4UxV+IfFD5+VddkvtbaptM)
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: POST
          github:
            clientId: ${custom.github.client-id}
            client-secret: ${custom.github.client-secret}
            scope: read:user, user:email
          google:
            clientId: ENC(hSIi04R6g7gCu8jmuvbKIkVDQLgIj3RfcIov1f6iwwjYtwMqKhgQ4DzV7QYoJ92ZU83mjxgSRDsagDlxNcqyoUT8i2OnhuEbGQaA7kvt/Pc=)
            client-secret: ENC(Sy6gQZ0OSIHABvUqpBZKJOBMQFdW6zIHkBnGrHY8WKAhU+ZhOja0RyFww2CU1GNC)
            scope: profile, email
            redirect-uri: '${custom.site.baseUrl}/{action}/oauth2/code/{registrationId}'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
openai:
  token: ENC(oJ6ZWiFlU8DaCj5rVcKrhHMX/IYcI/HYC3FFfX9dY7OTC2HKBHyOoQ2rQNIgfzzzjzhl4JF0l3TdI8O8fpa6Rg==)

scheduler:
  cron:
    job: "0 0 4 * * *"

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

accessKey:
  saramin: ENC(vAiGCHWxA7xlfVU04DkiksG8V05r4NKVzDoqYA8WbkmF7O6g6pZ/RxidyvQ4YppZd9suBjOz0lHSBVSFQ0NqkA==)

custom:
  jwt:
    secretKey: ENC(td8jcP/eOBMP9/6Nph0R0lmIzC5mhwk5ln46rp4GVt1mfwzI+J9YkA/bnu9dGxkzxRZk9k2dTWGmNUL2BLxVwQ==)
  github:
    client-id: ENC(Iem24CVhksoo9X1oT5QZzQa9xbAIuW9V2+Ym5HHpOCI=)
    client-secret: ENC(hX0VNKg0dVX4qsjqVsA/KmedU8mY9Bc659TBeiFXkxXCwRuTmJ87y6/AVuC0DPp9POJkzcEthRU=)
  site:
    baseUrl: http://localhost:8080
