server:
  port: 8080

spring:
  application:
    name: goodjob
  batch:
    jdbc:
      initialize-schema: always
  profiles:
    active: local

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: message/messages
    encoding: UTF-8

jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
openai:
  token: ENC(oJ6ZWiFlU8DaCj5rVcKrhHMX/IYcI/HYC3FFfX9dY7OTC2HKBHyOoQ2rQNIgfzzzjzhl4JF0l3TdI8O8fpa6Rg==)

scheduler:
  cron:
    job: "0 */5 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

accessKey:
  saramin: ENC(vAiGCHWxA7xlfVU04DkiksG8V05r4NKVzDoqYA8WbkmF7O6g6pZ/RxidyvQ4YppZd9suBjOz0lHSBVSFQ0NqkA==)
custom:
  jwt:
    secretKey: ENC(td8jcP/eOBMP9/6Nph0R0lmIzC5mhwk5ln46rp4GVt1mfwzI+J9YkA/bnu9dGxkzxRZk9k2dTWGmNUL2BLxVwQ==)


