server:
  port: 8080

spring:
  batch:
    jdbc:
      initialize-schema: always
  profiles:
    active: local

  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  messages:
    basename: message/messages
    encoding: UTF-8
jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
openai:
  token: ENC(2s7L+EDKX4PVEWHg43Ucs7pKFygFMQg4o8XBKynBx6cB3lUUeTh3yW1HcAMJcYImHWcXHN8c+PuUVnb1vUrViw==)

scheduler:
  cron:
    job: "0 */5 * * * *"