spring:
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    replication:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ENC(mAVSIC58xLOew8Eoqox+hA==)
      password: ENC(SJoUAh3qgBbC8t7APRidV6fgQ3+npv3n)
      write:
        name: write
        url: ENC(PSmFWkbu9dVJxnXbKCLfnolNzewXeC2saFlG7ucozYRMGVwlQMAzN2rfwue/a3Zyy0nDeOCabjFxy5aKUxo92j11QfoUbGs5j12+oWN8MIOeBn2Q75nd86EEDQKhL1JiY7JW6zn/glhFpkY5DOtQwEFeP50GBhVl)
      reads:
        - name: read1
          url: ENC(d+8j9c1Mn1isCh9MfkLbu3P5VhSNfdHNtgeYsGtkYim0WcaZm85ge8e1dKA4NojmfyHU2YenILyYSS2QBGdmM0v1yaC32FSzGh0jT6wghJFFZ1wzjeieN1CSgaiwaFNqZRwD8V1OAAjmaBqj0AJS7wFsQqmFL43Okn7PmrFftXw=)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

custom:
  github:
    client-id: ENC(KP2uJoq4/fKHp20/Ko41G8roZAGa30C75XkuWdpKeKI=)
    client-secret: ENC(JdURofDmvQR3TiWNh+VdqlazykNYaNutWoQ9p1hk332miNDiAHR7wyhKXSivCebe1kTZ+TIC8Ic=)
  site:
    baseUrl: https://waveofmymind.shop
  kafka:
    topic:
      question: question-prod
      advice: advice-prod
      job: job-prod

scheduler:
  cron:
    job: "0 0 4 * * *"
